# Generated by Django 5.1 on 2025-01-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
        ("users", "0002_alter_school_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team_member",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="isA",
                to="users.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team_member",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="has",
                to="team.team",
            ),
            preserve_default=False,
        ),
    ]
