# Generated by Django 5.1 on 2025-01-24 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
        ("users", "0002_school_is_country_school_type_student_attendent_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="grades",
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time_added", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="team.team"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="team",
            name="students",
            field=models.ManyToManyField(through="team.TeamMember", to="users.student"),
        ),
        migrations.DeleteModel(
            name="Team_member",
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("student", "team"), name="unique_student_team"
            ),
        ),
    ]
