services:
  db:
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-.}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    env_file: ./server/.env
    ports:
      - 5432:5432
  server:
    image: ${DOCKERHUB_USERNAME}/wajo-prod-server:latest
    container_name: wajo_server
    restart: unless-stopped
    env_file: ./.env.server
    entrypoint: /entrypoint.sh
    volumes:
      - ./opt/gunicorn-logs/:/var/log/gunicorn/
      - ./opt/django-logs/:/var/log/django/
      - ./opt/static_files/:/app/static_files
      - ./opt/media/:/app/mediafiles/media
    depends_on:
      - db
  client:
    image: ${DOCKERHUB_USERNAME}/wajo-prod-client:latest
    container_name: wajo-client
    restart: unless-stopped
    env_file: ./.env.client
    ports:
      - 3000:3000
    depends_on:
      - server

  nginx:
    image: nginx
    container_name: wajo_nginx
    restart: unless-stopped
    ports:
      - 80:3000
      - 443:3000
      - 3000:3000
      - 8000:8000
    volumes:
      - ./custom.conf:/etc/nginx/conf.d/default.conf
      - ./opt/static_files:/opt/static_files
      - ./opt/media:/opt/media
      - ./opt/nginx-logs/:/var/log/nginx/
    depends_on:
      - client
      - server

  watchtower:
    image: containrrr/watchtower
    container_name: wajo_watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
