# Generated by Django 5.1.5 on 2025-01-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateField()),
                ("address", models.CharField()),
                ("amount_of_students", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("subject", models.CharField(default="Registration", max_length=100)),
                (
                    "school_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.school"
                    ),
                ),
            ],
        ),
    ]
