# Generated by Django 5.1 on 2025-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_country",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="school",
            name="type",
            field=models.TextField(
                choices=[
                    ("Public", "Public"),
                    ("Independent", "Independent"),
                    ("Catholic", "Catholic"),
                ],
                default="Public",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="attendent_year",
            field=models.IntegerField(default=2025),
        ),
    ]
