# Generated by Django 5.1 on 2025-01-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_school_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_country",
            field=models.BooleanField(default=False),
        ),
    ]
