# Generated by Django 5.1 on 2025-01-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_school_is_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="type",
            field=models.TextField(
                choices=[
                    ("Public", "Public"),
                    ("Independent", "Independent"),
                    ("Catholic", "Catholic"),
                ],
                default="Public",
            ),
            preserve_default=False,
        ),
    ]
