# Generated by Django 5.1.5 on 2025-02-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_school_abbreviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="type",
            field=models.TextField(
                choices=[
                    ("Public", "Public"),
                    ("Independent", "Independent"),
                    ("Catholic", "Catholic"),
                    ("Allies", "Allies"),
                ],
                default="Public",
            ),
        ),
    ]
