# Generated by Django 5.1.6 on 2025-03-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='plaintext_password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
