# Generated by Django 5.1 on 2024-12-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoices",
            fields=[
                ("invoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("school_id", models.IntegerField()),
                ("quiz_id", models.IntegerField()),
                ("amount", models.FloatField(default=0)),
                ("issued_date", models.DateField(auto_now_add=True)),
                ("due_date", models.DateField(verbose_name="Due Date")),
                ("status", models.CharField(max_length=50)),
                ("number_of_teams", models.IntegerField()),
            ],
        ),
    ]
