# Generated by Django 5.1 on 2024-12-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Invoices",
            new_name="Invoice",
        ),
    ]
