/**
 * API Route Handler for fetching question data.
 *
 * This handler responds to API requests by returning a mock list of questions.
 * It is used to simulate the backend behavior and serve static question data.
 *
 * @fileoverview API endpoint located at `/api/questions` for fetching mock question data.
 *
 * @module /api/questions
 * @see {@link https://nextjs.org/docs/pages/building-your-application/routing/api-routes | Next.js API Routes Documentation}
 */

import { NextApiRequest, NextApiResponse } from "next";

// Mock data representing question entries
const mockQuestions: Question[] = [
  {
    name: "Question01_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question02_2024",
    genre: "Algebra Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question03_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question04_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question05_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question06_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question07_2024",
    genre: "Calculus Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question08_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question09_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question10_2024",
    genre: "Calculus Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question11_2024",
    genre: "Calculus Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question12_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question13_2024",
    genre: "Probability Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question14_2024",
    genre: "Trigonometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question15_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question16_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question17_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question18_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question19_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question20_2024",
    genre: "Trigonometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question21_2024",
    genre: "Algebra Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question22_2024",
    genre: "Geometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question23_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question24_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question25_2024",
    genre: "Probability Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question26_2024",
    genre: "Trigonometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question27_2024",
    genre: "Algebra Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question28_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question29_2024",
    genre: "Arithmetic Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question30_2024",
    genre: "Probability Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question31_2024",
    genre: "Trigonometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question32_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question33_2024",
    genre: "Geometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question34_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question35_2024",
    genre: "Arithmetic Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question36_2024",
    genre: "Statistics Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question37_2024",
    genre: "Calculus Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question38_2024",
    genre: "Probability Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question39_2024",
    genre: "Trigonometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question40_2024",
    genre: "Algebra Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question41_2024",
    genre: "Geometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question42_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question43_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question44_2024",
    genre: "Probability Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question45_2024",
    genre: "Trigonometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question46_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question47_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question48_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question49_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question50_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question51_2024",
    genre: "Probability Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question52_2024",
    genre: "Trigonometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question53_2024",
    genre: "Algebra Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question54_2024",
    genre: "Geometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question55_2024",
    genre: "Arithmetic Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question56_2024",
    genre: "Statistics Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question57_2024",
    genre: "Calculus Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question58_2024",
    genre: "Probability Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question59_2024",
    genre: "Trigonometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question60_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question61_2024",
    genre: "Geometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question62_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    name: "Question63_2024",
    genre: "Arithmetic Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
];

/**
 * Handles API requests to fetch question data.
 *
 * @function
 * @name handler
 * @param {NextApiRequest} _req - The API request object.
 * @param {NextApiResponse<Question[]>} res - The API response object to return the question data.
 *
 * @returns {void} Responds with a status code of 200 and the mock question data in JSON format.
 */
export default function handler(
  _req: NextApiRequest,
  res: NextApiResponse<Question[]>,
): void {
  res.status(200).json(mockQuestions);
}
