/**
 * API Route Handler for fetching question data.
 *
 * This handler responds to API requests by returning a mock list of questions.
 * It is used to simulate the backend behavior and serve static question data.
 *
 * @fileoverview API endpoint located at `/api/questions` for fetching mock question data.
 *
 * @module /api/questions
 * @see {@link https://nextjs.org/docs/pages/building-your-application/routing/api-routes | Next.js API Routes Documentation}
 */

import { NextApiRequest, NextApiResponse } from "next";

import { Question } from "@/types/question";

// Mock data representing question entries
const mockQuestions: Question[] = [
  {
    id: 1,
    name: "Question01_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 2,
    name: "Question02_2024",
    genre: "Algebra Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 3,
    name: "Question03_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 4,
    name: "Question04_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 5,
    name: "Question05_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 6,
    name: "Question06_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 7,
    name: "Question07_2024",
    genre: "Calculus Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 8,
    name: "Question08_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 9,
    name: "Question09_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 10,
    name: "Question10_2024",
    genre: "Calculus Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 11,
    name: "Question11_2024",
    genre: "Calculus Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 12,
    name: "Question12_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 13,
    name: "Question13_2024",
    genre: "Probability Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 14,
    name: "Question14_2024",
    genre: "Trigonometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 15,
    name: "Question15_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 16,
    name: "Question16_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 17,
    name: "Question17_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 18,
    name: "Question18_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 19,
    name: "Question19_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 20,
    name: "Question20_2024",
    genre: "Trigonometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 21,
    name: "Question21_2024",
    genre: "Algebra Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 22,
    name: "Question22_2024",
    genre: "Geometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 23,
    name: "Question23_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 24,
    name: "Question24_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 25,
    name: "Question25_2024",
    genre: "Probability Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 26,
    name: "Question26_2024",
    genre: "Trigonometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 27,
    name: "Question27_2024",
    genre: "Algebra Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 28,
    name: "Question28_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 29,
    name: "Question29_2024",
    genre: "Arithmetic Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 30,
    name: "Question30_2024",
    genre: "Probability Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 31,
    name: "Question31_2024",
    genre: "Trigonometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 32,
    name: "Question32_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 33,
    name: "Question33_2024",
    genre: "Geometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 34,
    name: "Question34_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 35,
    name: "Question35_2024",
    genre: "Arithmetic Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 36,
    name: "Question36_2024",
    genre: "Statistics Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 37,
    name: "Question37_2024",
    genre: "Calculus Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 38,
    name: "Question38_2024",
    genre: "Probability Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 39,
    name: "Question39_2024",
    genre: "Trigonometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 40,
    name: "Question40_2024",
    genre: "Algebra Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 41,
    name: "Question41_2024",
    genre: "Geometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 42,
    name: "Question42_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 43,
    name: "Question43_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 44,
    name: "Question44_2024",
    genre: "Probability Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 45,
    name: "Question45_2024",
    genre: "Trigonometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 46,
    name: "Question46_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 47,
    name: "Question47_2024",
    genre: "Geometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 48,
    name: "Question48_2024",
    genre: "Arithmetic Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 49,
    name: "Question49_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 50,
    name: "Question50_2024",
    genre: "Calculus Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 51,
    name: "Question51_2024",
    genre: "Probability Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 52,
    name: "Question52_2024",
    genre: "Trigonometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 53,
    name: "Question53_2024",
    genre: "Algebra Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 54,
    name: "Question54_2024",
    genre: "Geometry Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 55,
    name: "Question55_2024",
    genre: "Arithmetic Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 56,
    name: "Question56_2024",
    genre: "Statistics Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 57,
    name: "Question57_2024",
    genre: "Calculus Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 58,
    name: "Question58_2024",
    genre: "Probability Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 59,
    name: "Question59_2024",
    genre: "Trigonometry Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 60,
    name: "Question60_2024",
    genre: "Statistics Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 61,
    name: "Question61_2024",
    genre: "Geometry Questions",
    difficulty: "Easy",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 62,
    name: "Question62_2024",
    genre: "Algebra Questions",
    difficulty: "Medium",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
  {
    id: 63,
    name: "Question63_2024",
    genre: "Arithmetic Questions",
    difficulty: "Difficult",
    question: "What is the area of a circle with radius 5?",
    answer: "78.54",
    solution: "A = πr² = π(5)² = 78.54",
  },
];

/**
 * Handles API requests to fetch question data.
 *
 * @function
 * @name handler
 * @param {NextApiRequest} _req - The API request object.
 * @param {NextApiResponse<Question[]>} res - The API response object to return the question data.
 *
 * @returns {void} Responds with a status code of 200 and the mock question data in JSON format.
 */
export default function handler(
  _req: NextApiRequest,
  res: NextApiResponse<Question[]>,
): void {
  res.status(200).json(mockQuestions);
}
