# Generated by Django 5.1 on 2025-01-16 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question", "0001_initial"),
        ("users", "0002_remove_student_first_name_remove_student_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("intro", models.TextField()),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_comp", models.BooleanField(default=False)),
                ("visible", models.BooleanField(default=False)),
                ("open_time_date", models.DateTimeField(default=None)),
                ("close_time_date", models.DateTimeField(default=None)),
                ("time_limit", models.IntegerField(default=120)),
            ],
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("current_page", models.IntegerField()),
                ("state", models.IntegerField()),
                ("time_start", models.DateTimeField(auto_now_add=True)),
                ("time_finish", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                ("total_marks", models.IntegerField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="users.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizSlot",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("slot", models.IntegerField(db_index=True)),
                ("block", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="question.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="quiz.quiz",
                    ),
                ),
            ],
        ),
    ]
