# Generated by Django 5.1 on 2025-01-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
        ("quiz", "0001_initial"),
        ("users", "0002_alter_school_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizattemptuser",
            name="student",
        ),
        migrations.AddField(
            model_name="quizattemptuser",
            name="student_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_id",
                to="users.student",
            ),
        ),
        migrations.AddField(
            model_name="quizslots",
            name="question_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.question",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="state",
            field=models.CharField(
                choices=[
                    ("STATE_UNATTEMPTED", "Unattempted"),
                    ("STATE_IN_PROGRESS", "In Progress"),
                    ("STATE_COMPLETED", "Completed"),
                ]
            ),
        ),
    ]
