# Generated by Django 5.1 on 2025-01-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
