# Generated by Django 5.1 on 2025-01-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_quizslot_quiz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizslot",
            old_name="slot",
            new_name="slot_index",
        ),
    ]
