# Generated by Django 5.1 on 2025-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_quiz_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="time_window",
            field=models.IntegerField(default=10),
        ),
    ]
