# Generated by Django 5.1 on 2025-01-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quizslot_alter_quizattempt_quiz_id_delete_quizslots"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="grade",
            new_name="total_marks",
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="state",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="quizslot",
            name="status",
            field=models.IntegerField(),
        ),
    ]
