# Generated by Django 5.1 on 2025-01-21 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_remove_quiz_close_time_date"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionattempt",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_attempts",
                to="users.student",
            ),
            preserve_default=False,
        ),
    ]
