# Generated by Django 5.1 on 2025-01-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_questionattempt_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionattempt",
            name="answer_student",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="time_finish",
            field=models.DateTimeField(),
        ),
    ]
