# Generated by Django 5.1 on 2025-01-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_questionattempt_answer_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "Unattempted"),
                    (2, "In Progress"),
                    (3, "Submitted"),
                    (4, "Completed"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="time_finish",
            field=models.DateTimeField(null=True),
        ),
    ]
