# Generated by Django 5.1.5 on 2025-01-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_questionattempt_answer_student'),
        ('quiz', '0007_alter_quizattempt_state_and_more'),
    ]

    operations = [
    ]
