# Generated by Django 5.1.5 on 2025-01-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_quizattempt_team"),
        ("team", "0003_alter_teammember_student_alter_teammember_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="team",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="team.team",
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="time_finish",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
