# Generated by Django 5.1.5 on 2025-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_quizattempt_dead_line_alter_quizattempt_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
