# Generated by Django 5.1.5 on 2025-01-27 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_alter_quizattempt_student"),
        ("users", "0002_school_is_country_school_type_student_attendent_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="student",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="users.student",
            ),
        ),
    ]
