# Generated by Django 5.1.6 on 2025-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_image_jax_text_remove_image_scale_and_more'),
        ('quiz', '0012_alter_quiz_open_time_date_alter_quiz_time_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizslot',
            name='quiz_question_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        # migrations.AddConstraint(
        #     model_name='quizslot',
        #     constraint=models.UniqueConstraint(fields=('quiz', 'quiz_question_id'), name='unique_quiz_question_id_per_quiz'),
        # ),
    ]
