# Generated by Django 5.1.5 on 2025-01-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_alter_quizattempt_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="dead_line",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
