# Generated by Django 5.1 on 2024-12-06 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=200)),
                ("mark", models.FloatField()),
                ("image", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("answer_id", models.AutoField(primary_key=True, serialize=False)),
                ("answer", models.FloatField()),
                (
                    "question_id",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question.question",
                    ),
                ),
            ],
        ),
    ]
