# Generated by Django 5.1 on 2024-12-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="question_id",
            new_name="question",
        ),
    ]
