# Generated by Django 5.1 on 2025-01-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionAttempt",
        ),
    ]
