# Generated by Django 5.1.5 on 2025-01-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="answer_text",
        ),
        migrations.AddField(
            model_name="question",
            name="solution_text",
            field=models.TextField(default=""),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="question.question",
                    ),
                ),
            ],
        ),
    ]
