# Generated by Django 5.1 on 2025-01-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="diff_level",
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("EASY", "Easy"), ("MEDIUM", "Medium"), ("HARD", "Hard")],
                default="Easy",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
