# Generated by Django 5.1 on 2025-01-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="genre",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
