# Generated by Django 5.1 on 2025-01-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_remove_question_difficulty_category_diff_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="diff_level",
            field=models.TextField(
                choices=[
                    ("Easy", "Easy"),
                    ("Medium", "Medium"),
                    ("Difficult", "Difficult"),
                ],
                default="Medium",
            ),
        ),
    ]
