# Generated by Django 5.1 on 2025-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_alter_category_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="category",
        ),
        migrations.AddField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="questions", to="question.category"
            ),
        ),
    ]
