# Generated by Django 5.1.5 on 2025-02-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "question",
            "0002_remove_question_answer_remove_question_answer_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="jax_text",
        ),
        migrations.RemoveField(
            model_name="image",
            name="scale",
        ),
        migrations.RemoveField(
            model_name="question",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="question.question",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
