name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Get date for tagging
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/server/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/wajo-prod-server:latest
            ${{ vars.DOCKERHUB_USERNAME }}/wajo-prod-server:${{ env.date }}

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v4

      - name: Get date for tagging
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Client Docker image
      - name: Build and push the client Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/client/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/wajo-prod-client:latest
            ${{ vars.DOCKERHUB_USERNAME }}/wajo-prod-client:${{ env.date }}
